import os
import boto3
from dotenv import load_dotenv

load_dotenv()



access_token = 'eyJraWQiOiJ5Y3haOGgwNnRnY2IrSDA0czEyUmFDbnptajhZMjJMTXlueG84b0JBcG1zPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI2NjU2MmIwZi01OTUzLTQyYTAtOTgwNS1jNzcxY2RlYjgzNGYiLCJldmVudF9pZCI6ImM2MzkxZjc4LWUzYjktNGEwZi1iMDQ3LTg3ZWQwNmNlOTRlMCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2MjMxNjk5MjMsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTIuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0yX1pVUGgwV0Y1VCIsImV4cCI6MTYyMzE3MzUyMywiaWF0IjoxNjIzMTY5OTIzLCJqdGkiOiJkMWY4YTA3Yi03MGM3LTQ0ZDgtYWI3YS0yODEzNzUzYmM2MGQiLCJjbGllbnRfaWQiOiI0ZnBub2tycXRva2c1NWhjczM5OTJoNmhtdCIsInVzZXJuYW1lIjoiNjY1NjJiMGYtNTk1My00MmEwLTk4MDUtYzc3MWNkZWI4MzRmIn0.OlyBGMEi9GJ1wvEOMfMIEsmCbKRz47-WUsJ3F1w1pBcdncX-upJ66NQqQ0uvedPkxGsZ14gqrmiN15JAMO2AeDHxSHuG1MHg-fxpmN5zfkyFhDusTHLYeN-caWAPp9eTrTGpePmLBCmsz9qTdHdLWVxNULM77mt4ml0STCGNPa8vBRvv6_-tpkCSAYkrY7Gupc_liYBRcCiGGbjsOv_7qepRiL-3fLDoOqlnDWQDdc6UmyYoiHsSYmw87FUkVDNcDIDm6i3GR0nbGHg3beEWgzju6uorwKDHcy9Wn0VRlagkgJKpUTZ6O1jpksM5AnrwvS8SgejTTkp_kiNJ_FyIYQ'

previous_password = 'Mani@321'
new_password = 'Mani@123'


client = boto3.client('cognito-idp', region_name=os.getenv('COGNITO_REGION_NAME'))
response = client.change_password(
    PreviousPassword = previous_password,
    ProposedPassword = new_password,
    AccessToken = access_token
)

print(response)